### ISSUE TITLE
增加position: "center center"

### ISSUE THREAD

**Issue by lanbos** [chengxulvtu/cxlt-vue2-toastr#21]
在自己的样式文件中增加（less）：
```less
.toast-center-center {
  position: fixed;
  left: 0px;
  right: 0px;
  top: 50%;
  transform: translateY(-50%);
  .toast {
    width: 90%;
    margin-left: 5%;
    line-height: 1.8;
    padding: 16px 15px 15px 50px;
    .toast-title {
      font-weight: normal;
    }
  }
}
```
